### ISSUE TITLE
missing reference

### ISSUE THREAD

**Issue by Xianjun-Yang** [ydyjya/Awesome-LLM-Safety#1]
Hi,

Nice repo! I found my work (https://arxiv.org/abs/2310.02949) is not included in the attack, but it is the first work to remove safety by fine-tuning. 

It would be great if you could include it. Thanks!

**Comment by ydyjya** [comment]
Dear Xianjun-Yang,
Nice Work! It is inspired and I am glad to include it into my repo today. Have a nice day!🍻

Your faithfully,
Zhenghong Zhou
