### ISSUE TITLE
Request for including a paper

### ISSUE THREAD

**Issue by HengguangZhou** [ydyjya/Awesome-LLM-Safety#11]
Hi,

Great repo, I really enjoyed the paper you shared! I'm thinking you might be interested in our recently released benchmark, **"MOSSBench: Is Your Multimodal Language Model Oversensitive to Safe Queries?”** that sheds light on an interesting aspect of safety related model behavior—many “aligned” multimodal models over-react to harmless queries.

I’d love it if you could take a glance at our project summary and consider including this paper in your repo.

Here’s where you can find more details:
[Project](https://turningpoint-ai.github.io/MOSSBench/)
[Paper](https://arxiv.org/pdf/2406.17806)

Thanks for your time and consideration!

**Comment by ydyjya** [comment]
Thank you for pointing out the missing! I will add your great paper this week! 😊
