### ISSUE TITLE
Include recent work on PII leakage

### ISSUE THREAD

**Issue by KKNakkav2** [ydyjya/Awesome-LLM-Safety#14]
Hi,

Thank you for maintaining this repo.

Can you include our recent work https://arxiv.org/abs/2407.02943 PII-Compass: Guiding LLM training data extraction prompts towards the target PII via grounding, PrivateNLP Workshop, ACL 2024 to the Privacy section.

Thank you in advance.

**Comment by ydyjya** [comment]
Nice Work!

Thank you for adding the paper to the repo. I will add this paper in the next update. 😊
