### ISSUE TITLE
A line of papers on recent "harmful fine-tuning" attack 

### ISSUE THREAD

**Issue by huangtiansheng** [ydyjya/Awesome-LLM-Safety#19]
Hi authors,

Thanks for the wonderful repo. Recently there is a growing interest on harmful fine-tuning issue for LLMs. Could you please include this line of papers into your repo? 

We also maintain a survey&repo speficially for attacks/defenses for harmful fine-tuning. Please feel free to check them out. 

Harmful Fine-tuning Attacks and Defenses for Large Language Models: A Survey https://arxiv.org/abs/2409.18169

Repo: https://github.com/git-disl/awesome_LLM-harmful-fine-tuning-papers

**Comment by ydyjya** [comment]
Hello, thank you for your comprehensive and insightful work!

I have added your work to the repository, and the repo you maintain is very helpful, so I have also added it to the README.

**Comment by huangtiansheng** [comment]
Thank you!
