### ISSUE TITLE
new paper

### ISSUE THREAD

**Issue by yueliu1999** [ydyjya/Awesome-LLM-Safety#21]
Thanks for your amazing repo!

We have one paper which may be highly related to this topic:

[FlipAttack: Jailbreak LLMs via Flipping](https://arxiv.org/pdf/2410.02832)

**Comment by ydyjya** [comment]
Hi~ 

Your research is impressive and insightful. We have added your paper at line 312 of `subtopic/Jailbreaks&Attack.md`. 

Thank you for your interest in our repo!
