### ISSUE TITLE
Request for paper inclusion

### ISSUE THREAD

**Issue by AmenRa** [ydyjya/Awesome-LLM-Safety#24]
Thank you for this great repo! I would be delighted if our work could also be included.
It is both a research paper, a benchmark, and a Python library on/for the evaluation of guardrail models (e.g., Llama Guard).

- Title: GuardBench: A Large-Scale Benchmark for Guardrail Models
- Venue: EMNLP 2024
- Paper: https://aclanthology.org/2024.emnlp-main.1022.pdf
- Code: https://github.com/AmenRa/guardbench
- Classification: Datasets & Benchmark
- Tags: guardrail models, safety, benchmark, evaluation

Thanks,

Elias

**Comment by ydyjya** [comment]
Insightful Paper! I have added the paper! in `update 12.7`.

If you have additional research, feel free to let me add it!

**Comment by AmenRa** [comment]
Thank you! :)
